version: '3.9'

services:
  postgres:
    image: docker.io/postgres:latest
    container_name: main-postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - ../.env

volumes:
  postgres_data:
