# Generated by Django 5.0.6 on 2024-06-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customermodel_token'),
        ('products', '0002_rename_product_productmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Product is active'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Product name'),
        ),
        migrations.CreateModel(
            name='ProductReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rating', models.PositiveSmallIntegerField(default=1, verbose_name='User rating')),
                ('text', models.TextField(blank=True, default='', max_length=1024, verbose_name='Review text')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='customers.customermodel', verbose_name='Reviewer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.productmodel', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product reviews',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
